### ISSUE TITLE
在使用mian.py时遇到的几个问题。

### ISSUE THREAD

**Issue by tylercross** [thu-media/Tiyuntsong#1]
您好，我按照readme中的指示，在直接使用您的tiyuntsong-final中的 main.py 训练时遇到了如下的问题。
1、在调用sabre时，为什么我会有提示说算术错误，也就是除数为0了。[sabre中:line 118, 601, 606]]我的解决方法是为除数加0.001。我也对比了原始的sabre中对应的部分，和原始的sabre在这些部分没有改动。我非常好奇是否您在仿真中遇到这个问题？
2、我在执行训练时，经过500个epoch，曲线如下图所示：
![0f4a2e3926ef97f76bae267dc98ad25](https://user-images.githubusercontent.com/29889956/51798252-e23bb980-224a-11e9-9d30-40c887696c35.png)
但是使用您的elo.txt中画出来的图形如下：
![bd46c680d9d47361f76884eb06dedd9](https://user-images.githubusercontent.com/29889956/51798264-11eac180-224b-11e9-96d7-423cce1d4d10.png)
显而易见，您的曲线有着很好的上升趋势，两条曲线的值也基本保持在一个稳定的范围，我跑出的曲线趋势不明显，并且有着很大的波动，两个agnet的曲线的差值也有着很大的波动。非常好奇您的曲线为何与我的不同。
3.另外尽管elo.txt中显示的是在1000以下的地方波动，但是best.txt中又有着更新，甚至数值上超过您默认的数值。
700.0923496712602
719.048347361147
...

1012.2858863312995

717.6171635683997
...
1019.18198292
3. 另外我理解Multi.py 是用来通过多进程加速训练。但是我尝试使用它时，发现它卡在了某个地方，不太明白在哪里出了问题。
4.对您论文中给出的几个其他abr算法的elo值作为对比数值，您可以分享更多有关如何得到这几个数值的细节吗？

**Comment by godka** [comment]
您好~感谢关注我们的工作！
1. 我从没遇到过这个问题，我使用的python环境为py3.6+，请确认一下是不是因为python版本的不同造成?
2. 不知道您画的epoch的曲线图是training set还是test set的。ABR任务比较特殊，不同的trace有不同的reward peak，如果单纯画training set的话是一篇混乱的。所以一般是隔一段时间画一次test set，我们的工作中elo.txt就是初始选择了一部分数据作为测试集的结果。
3. 接着2的思路，best就是一个记录A和B的最佳记录的模型。
4. Multi.py是之前想写的一个multi-agent训练，但是考虑到单进程效率也还行，所以就暂时搁置了。（就目前来说效率比单进程慢，我们也正在改进中。）
5. elo是在任务初始时首先将过去的abr算法在随机选出的测试集上做了测试，并且相互计算了胜率。详细的说：最开始abr算法的默认elo都是1000，随后将根据我们定义的规则对胜率进行调配。所以对于每个算法的分数来说，每次生成都有细微区别，但是不会影响到整体。

您提的大部分问题可以在https://github.com/thu-media/Tiyuntsong/blob/7bb9392d86e83f1b9329aba187248aa4c4ccd3e5/src/tracepool.py#L36
中查看到答案。

最后再次感谢您对我们工作的关注。

**Comment by tylercross** [comment]
非常感谢您如此高效的回复。
1、可能是我的Python与您的Python存在版本差异导致，我将升级我的环境，再次尝试。
2、我画的这个elo图，是main中在训练过程中自动记录到elo中，并自动调用draw.py。从代码看应该是test中达到到的elo值。
https://github.com/thu-media/Tiyuntsong/blob/7bb9392d86e83f1b9329aba187248aa4c4ccd3e5/src/main.py#L84
所以我的elo理论上应该和您的比较相似。可以认为是因为随机的抽取的测试集等环节引入的随机性导致这样的不同？
3、best模型最终会存放在0-model和1-model，现在的训练每次似乎是从头开始训练，重新初始化各个网络，调用播放器获得state，然后PK,找到最高得分的elo，但是如果直接restore出最优的模型进行pk，并作为训练部分的起点，是否会更有效果？
4和5 理解。
另外，还有一个小问题：
6、您在文章3.3中指出，Dynamic learning rate can avoid a huge gap between the two apgents。这里有具体的依据吗，按公式（6）的表面来看，当胜率越大时更新幅度越小，胜率越小更新幅度越小，只有当胜率在0.3和0.4之间取最大。请您指教。
![for_six](https://user-images.githubusercontent.com/29889956/51800497-681b2d00-226a-11e9-9a8a-a38063203014.png)
还有个问题，下面的代码中似乎和公式（6）中弄条件弄反了，不知道应该以那个为准？
https://github.com/thu-media/Tiyuntsong/blob/7bb9392d86e83f1b9329aba187248aa4c4ccd3e5/src/dualgan.py#L167

**Comment by godka** [comment]
2. 我也不太清楚，我当时在测试中没有出现这类问题。或许可能是因为6的问题。
6. 感谢您提供了这个BUG，是我们疏忽导致。我们将重新测试其稳定性。
该公式是熵公式的扩展，基本上是试出来的，我们试了三次方程，熵扩展，截断等方法，最终选取了一个可行的方案。

再次感谢您对我们论文的关注，我们将会在实验室测试其正确性。

不过从我们之前的实验来看，改动
https://github.com/thu-media/Tiyuntsong/blob/7bb9392d86e83f1b9329aba187248aa4c4ccd3e5/src/dualgan.py#L186
这边的lr会起到更多作用，后者entropy可能由于beta=0.01太小了没有起太大作用。
